#spring:
#  application:
#    name: demo-book-site
#  datasource: url:jdbc:mysql://localhost:3306/demo-book-site
#      username: ${USERNAME}
#      password: ${PASSWORD}
#
#  jpa:
#    hibernate.ddl-auto=update
#    show-sql=true
#    properties.hibernate.format_sql=true
#  logging:
#  level: org.hibernate.SQL=DEBUG
#  logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#  logging.level.org.springframework.data.jpa.repository=DEBUG
#  spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=${EMAIL}
#  spring.mail.password=lgwc ajdp xxjj cyuq
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#
#
